import { Call } from '@/types';

export const mockCalls: Call[] = [
  {
    id: '1',
    title: 'Investment Portfolio Review',
    category: 'investment',
    description: 'I want to review my current investment portfolio and get advice on rebalancing. My portfolio is heavily weighted in tech stocks and I\'m concerned about diversification.',
    goals: 'Optimize portfolio allocation to reduce risk while maintaining growth potential. Learn about international diversification options.',
    date: '2024-10-01',
    duration: '25:30',
    status: 'completed',
    agentName: 'Alex Financial AI',
    summary: 'Discussed diversification strategy and rebalancing options for current portfolio mix.',
    feedback: {
      rating: 5,
      comment: 'Very helpful session! The AI agent provided clear insights about my portfolio allocation and suggested practical rebalancing strategies.',
      helpfulness: 5,
      clarity: 4,
      timestamp: '2024-10-01T14:30:00Z',
    },
    report: {
      overview: 'The client\'s investment portfolio was analyzed for risk exposure and diversification. Current allocation shows 70% stocks, 20% bonds, and 10% cash equivalents.',
      keyPoints: [
        'Portfolio is heavily weighted towards technology sector (45%)',
        'Bond allocation is below recommended levels for age bracket',
        'Emergency fund is adequate at 6 months of expenses',
        'International exposure is limited to 15% of equity holdings',
      ],
      recommendations: [
        'Increase bond allocation to 30% to match age-appropriate risk profile',
        'Diversify technology holdings by adding international and value stocks',
        'Consider adding TIPS for inflation protection',
        'Maintain current emergency fund level',
      ],
      actionItems: [
        'Rebalance portfolio within next 30 days',
        'Set up automatic quarterly rebalancing',
        'Review international fund options',
        'Schedule follow-up in 6 months',
      ],
      riskAssessment: {
        level: 'medium',
        description: 'Portfolio has moderate risk due to concentration in technology sector. Recommended adjustments will reduce risk to appropriate levels.',
      },
      financialMetrics: [
        { label: 'Total Portfolio Value', value: '$485,000' },
        { label: 'YTD Returns', value: '+12.5%' },
        { label: 'Expense Ratio', value: '0.18%' },
        { label: 'Diversification Score', value: '6.5/10' },
      ],
    },
  },
  {
    id: '2',
    title: 'Retirement Planning Consultation',
    category: 'retirement',
    description: 'I\'m 42 years old and want to ensure I\'m on track for retirement at 65. Currently contributing 8% to my 401(k) with employer match.',
    goals: 'Maximize retirement savings and understand if I need to increase contributions. Explore Roth IRA options.',
    date: '2024-09-28',
    duration: '32:15',
    status: 'completed',
    agentName: 'Morgan Wealth AI',
    summary: 'Comprehensive retirement planning discussion covering 401(k) contributions, IRA options, and projected retirement income.',
    feedback: {
      rating: 5,
      comment: 'Excellent guidance on retirement planning. The projections and scenarios were eye-opening.',
      helpfulness: 5,
      clarity: 5,
      timestamp: '2024-09-28T10:45:00Z',
    },
    report: {
      overview: 'Conducted comprehensive retirement planning analysis for client aged 42. Current retirement savings are on track but could be optimized with increased contributions.',
      keyPoints: [
        'Currently contributing 8% to 401(k) with 4% employer match',
        'Projected retirement age: 65 (23 years from now)',
        'Current retirement savings: $245,000',
        'Estimated retirement income need: $85,000/year',
      ],
      recommendations: [
        'Increase 401(k) contribution to 15% to maximize growth potential',
        'Open Roth IRA and contribute maximum annual amount',
        'Consider backdoor Roth conversion for additional savings',
        'Diversify retirement accounts for tax optimization',
      ],
      actionItems: [
        'Update 401(k) contribution percentage to 15%',
        'Open Roth IRA account within 2 weeks',
        'Consult tax advisor about Roth conversion strategy',
        'Review Social Security benefits projection',
      ],
      riskAssessment: {
        level: 'low',
        description: 'Client is in good position for retirement with adequate time horizon. Recommended changes will further strengthen retirement readiness.',
      },
      financialMetrics: [
        { label: 'Current Retirement Savings', value: '$245,000' },
        { label: 'Projected at 65 (current pace)', value: '$1.2M' },
        { label: 'Projected at 65 (optimized)', value: '$1.8M' },
        { label: 'Annual Income Gap', value: '$25,000' },
      ],
    },
  },
  {
    id: '3',
    title: 'Debt Management Strategy',
    category: 'debt',
    description: 'I have $45,000 in total debt across credit cards and student loans. Looking for the best strategy to pay it off efficiently.',
    goals: 'Create a clear debt payoff plan that minimizes interest payments and gets me debt-free as quickly as possible.',
    date: '2024-09-25',
    duration: '18:45',
    status: 'completed',
    agentName: 'Alex Financial AI',
    summary: 'Developed a debt payoff strategy focusing on high-interest credit cards and student loans.',
    feedback: {
      rating: 4,
      comment: 'Good practical advice. Would have liked more discussion on debt consolidation options.',
      helpfulness: 4,
      clarity: 4,
      timestamp: '2024-09-25T16:20:00Z',
    },
    report: {
      overview: 'Analyzed client\'s debt portfolio totaling $45,000 across multiple accounts. Created prioritized payoff strategy to minimize interest payments.',
      keyPoints: [
        'Total debt: $45,000 across 3 credit cards and 1 student loan',
        'Average interest rate: 16.5% on credit cards',
        'Minimum monthly payments: $850',
        'Available monthly surplus: $600',
      ],
      recommendations: [
        'Use avalanche method to pay off highest interest debt first',
        'Transfer credit card balances to 0% APR card if approved',
        'Increase monthly debt payments to $1,450',
        'Avoid accumulating new credit card debt',
      ],
      actionItems: [
        'Apply for balance transfer credit card',
        'Set up automatic payments for minimum amounts',
        'Allocate full $600 surplus to highest interest card',
        'Track progress monthly using debt payoff calculator',
      ],
      riskAssessment: {
        level: 'medium',
        description: 'High-interest debt presents moderate financial risk. Following recommended strategy will eliminate debt in 36 months.',
      },
      financialMetrics: [
        { label: 'Total Debt', value: '$45,000' },
        { label: 'Average Interest Rate', value: '16.5%' },
        { label: 'Payoff Timeline (current)', value: '68 months' },
        { label: 'Payoff Timeline (optimized)', value: '36 months' },
      ],
    },
  },
  {
    id: '4',
    title: 'Home Purchase Financial Assessment',
    date: '2024-09-20',
    duration: '28:00',
    status: 'completed',
    agentName: 'Morgan Wealth AI',
    summary: 'Evaluated readiness for home purchase including down payment, mortgage options, and affordability analysis.',
    feedback: {
      rating: 5,
      comment: 'This session gave me the confidence to move forward with my home purchase plans!',
      helpfulness: 5,
      clarity: 5,
      timestamp: '2024-09-20T13:15:00Z',
    },
    report: {
      overview: 'Assessed client\'s financial readiness for home purchase in target price range of $400,000-$450,000. Analysis indicates strong position with adequate savings and income.',
      keyPoints: [
        'Down payment savings: $95,000 (ready for 20% down)',
        'Annual household income: $145,000',
        'Current debt-to-income ratio: 18%',
        'Credit score: 780 (excellent)',
      ],
      recommendations: [
        'Target homes in $425,000 range for optimal affordability',
        'Maintain 20% down payment to avoid PMI',
        'Lock in current mortgage rates (around 6.5%)',
        'Keep 6 months expenses in emergency fund after purchase',
      ],
      actionItems: [
        'Get pre-approved for mortgage up to $450,000',
        'Compare rates from at least 3 lenders',
        'Budget for closing costs ($12,000-$15,000)',
        'Start house hunting in targeted neighborhoods',
      ],
      riskAssessment: {
        level: 'low',
        description: 'Client is well-prepared for home purchase with strong financial foundation. Recommended price range aligns with income and savings.',
      },
      financialMetrics: [
        { label: 'Target Home Price', value: '$425,000' },
        { label: 'Down Payment (20%)', value: '$85,000' },
        { label: 'Estimated Monthly Payment', value: '$2,680' },
        { label: 'Payment-to-Income Ratio', value: '22%' },
      ],
    },
  },
  {
    id: '5',
    title: 'Tax Optimization Strategy',
    date: '2024-09-15',
    duration: '22:30',
    status: 'completed',
    agentName: 'Alex Financial AI',
    summary: 'Explored tax-efficient investment strategies and discussed opportunities for tax loss harvesting.',
    feedback: {
      rating: 4,
      comment: 'Learned several new strategies. Will need to discuss with my tax advisor before implementing.',
      helpfulness: 4,
      clarity: 4,
      timestamp: '2024-09-15T11:30:00Z',
    },
    report: {
      overview: 'Reviewed client\'s tax situation and identified opportunities for tax optimization through strategic investment placement and tax loss harvesting.',
      keyPoints: [
        'Current marginal tax rate: 24%',
        'Holding mix of taxable and tax-advantaged accounts',
        'Unrealized losses available for harvesting: $8,500',
        'No Roth IRA contributions despite eligibility',
      ],
      recommendations: [
        'Harvest tax losses before year end to offset gains',
        'Relocate bond holdings to tax-advantaged accounts',
        'Begin contributing to Roth IRA ($7,000 annually)',
        'Consider municipal bonds for taxable accounts',
      ],
      actionItems: [
        'Execute tax loss harvesting trades within 30 days',
        'Rebalance account holdings for tax efficiency',
        'Open and fund Roth IRA before December 31',
        'Schedule meeting with CPA to review strategy',
      ],
      riskAssessment: {
        level: 'low',
        description: 'Tax optimization strategies carry minimal risk and can provide significant long-term benefits.',
      },
      financialMetrics: [
        { label: 'Potential Tax Savings', value: '$2,040' },
        { label: 'Current Tax Rate', value: '24%' },
        { label: 'Tax Loss Harvest Amount', value: '$8,500' },
        { label: 'Annual Tax Efficiency Gain', value: '$1,200' },
      ],
    },
  },
  {
    id: '6',
    title: 'Emergency Fund Assessment',
    date: '2024-09-10',
    duration: '15:20',
    status: 'completed',
    agentName: 'Morgan Wealth AI',
    summary: 'Quick consultation about building adequate emergency fund and choosing the right savings vehicles.',
    feedback: {
      rating: 5,
      comment: 'Short but very informative. Got exactly what I needed.',
      helpfulness: 5,
      clarity: 5,
      timestamp: '2024-09-10T09:15:00Z',
    },
    report: {
      overview: 'Evaluated client\'s emergency fund adequacy and recommended improvements to build financial resilience.',
      keyPoints: [
        'Current emergency fund: $8,000 (2 months expenses)',
        'Monthly essential expenses: $4,000',
        'Income stability: Moderate (commission-based role)',
        'Current savings: Traditional savings account at 0.5% APY',
      ],
      recommendations: [
        'Build emergency fund to $24,000 (6 months)',
        'Move funds to high-yield savings account (5.0% APY)',
        'Set up automatic monthly transfers of $800',
        'Keep funds liquid and easily accessible',
      ],
      actionItems: [
        'Open high-yield savings account this week',
        'Set up automatic transfer of $800/month',
        'Transfer existing $8,000 to new account',
        'Reassess fund adequacy in 12 months',
      ],
      riskAssessment: {
        level: 'medium',
        description: 'Current emergency fund is insufficient for income volatility. Building to 6 months will provide adequate cushion.',
      },
      financialMetrics: [
        { label: 'Current Emergency Fund', value: '$8,000' },
        { label: 'Target Emergency Fund', value: '$24,000' },
        { label: 'Monthly Gap to Close', value: '$16,000' },
        { label: 'Timeline to Goal', value: '20 months' },
      ],
    },
  },
];

